force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Priority__c.field-meta.xml
<CustomField>
    <fullName>Is_Priority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Priority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContactUpdater.cls
public class ContactUpdater {
    public static void markContactsProiority(){
        List<Account> goldAccounts = [Select Id,Tier__c from Account where Tier__c='Gold'];
         set<Id> goldAccountids = new set<Id>();
        for(Account acc : goldAccounts){
            goldAccountids.add(acc.Id);
        }
        List<Contact> relatedContacts =[select Id,Accountid from Contact where Accountid IN:goldAccountids];
        List<Contact> updatedContacts = new List<COntact>();
        for(Contact con: relatedContacts){
            con.Is_Priority__c=true;
            updatedContacts.add(con);
              
        }
        if(!updatedContacts.isEmpty()){
            update updatedContacts;
        }
    }
}