force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Discounted_Price__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Price__c</fullName>
    <label>Discounted Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ApplyDiscountCarsTest.cls
@isTest
private class ApplyDiscountCarsTest {
    @isTest static void ApplyDiscountTest(){
        Car__c Car =new Car__c();
        Car.Name='test car';
        Car.Original_Price__c=100000;
        Car.Discount__c=20;
        Test.StartTest();
        insert Car;
        Test.stopTest();
     Car__c carData =[Select Discounted_Price__c From Car__c Where Id=:Car.Id Limit 1] ;
        System.assertEquals(800000,  CarData.Discounted_Price__c);
    }
}