force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Max_Pay__c.field-meta.xml
<CustomField>
    <fullName>Max_Pay__c</fullName>
    <label>Max Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open Approved</fullName>
            </value>
            <value>
                <fullName>Closed Filled</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CarTriggerHandler.cls
public class CarTriggerHandler {
    public static void populateData(List<Car__c> cars){
        for(Car__c ca:cars){
            if(ca.Status__c == 'New Position'){
                if(ca.Open_Date__c == null){
                    ca.Open_Date__c = System.Today();
                }
                if(ca.Min_Pay__c == null){
                    ca.Min_Pay__c =10000;
                }
                if(ca.Max_Pay__c == NULL){
                    CA.Max_Pay__c = 15000;
                }
            }
        }
    }
    public static void CreateTask(List<Car__c> cars){
        List<Task> taskList = new List<Task>();
        for(Car__c ca: cars){
            Task t = new Task();
            t.Subject ='Follow up';
            t.ActivityDate = System.Today()+10;
            t.WhatId = ca.Id;
            t.OwnerId =UserInfo.getUserId();
            t.Status = 'Not Started';
            taskList.add(t);
        }
        if(!taskList.isEmpty()){
            insert taskList;
        }
        
    }
}