force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Post Poned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventBatchTest.cls
@isTest
public class EventBatchTest {
   public TestMethod static void Class_Event_Batch_Test_Method()
    {
        List<Event__c> eve_List = New List<Event__c>();
        Event__c eve = new Event__c();
        eve.Status__c = 'Deleted';
        eve_List.add(eve);
        Test.startTest();
        Database.SaveResult []str = Database.insert(eve_List,false);
        system.assertEquals(True, str[0].isSuccess());
        EventBatchDeleteStatus ev = New EventBatchDeleteStatus();
        Database.executeBatch(ev);
        Test.stopTest();
    }
}